INSERT INTO public.kaggle_ranking (rank, tier, username, points) VALUES (1, 'GrandMaster', 'Guanshuo Xu', 255613);
INSERT INTO public.kaggle_ranking (rank, tier, username, points) VALUES (2, 'GrandMaster', 'bestfitting', 212995);
INSERT INTO public.kaggle_ranking (rank, tier, username, points) VALUES (3, 'GrandMaster', 'Psi', 184945);
INSERT INTO public.kaggle_ranking (rank, tier, username, points) VALUES (4, 'GrandMaster', 'KazAnova', 164286);
INSERT INTO public.kaggle_ranking (rank, tier, username, points) VALUES (5, 'GrandMaster', 'Dieter', 154425);
INSERT INTO public.kaggle_ranking (rank, tier, username, points) VALUES (6, 'GrandMaster', 'Giba', 152913);
INSERT INTO public.kaggle_ranking (rank, tier, username, points) VALUES (7, 'Master', 'NQ', 117374);
INSERT INTO public.kaggle_ranking (rank, tier, username, points) VALUES (8, 'GrandMaster', 'Ahmet Erdem', 114918);
INSERT INTO public.kaggle_ranking (rank, tier, username, points) VALUES (9, 'GrandMaster', 'dott', 114756);
INSERT INTO public.kaggle_ranking (rank, tier, username, points) VALUES (10, 'GrandMaster', 'Ian Pan', 109115);